matrix:
  include:
  - language: node_js
    node_js:
      - "8"
    os:
      - linux
      - osx
    before_install:
      - sudo apt-get install libudev-dev
    before_script:
      - npm install
    script:
      - npm run eslint
